const universities = [
  {
    id: 1,
    name: "Beihang University",
    ranking: 1,
    location: "Beijing, China",
    about:
      "Beihang University is a prestigious higher education institution with a long history. Founded on October 25, 1952 under the name of Beijing Institute of Aeronautics, it originated from the merger of the aeronautical departments of Beijing Institute of Technology, Tsinghua University, and Sichuan University. In 1988, it was renamed Beijing University of Aeronautics and Astronautics (BUAA). In 2002, the university changed its English name to Beihang University.",
    fees: "$50,000 per year",
    accommodation:
      "The international student dormitory offers comfortable rooms equipped with essential amenities, including beds, desks, chairs, closets, air conditioners, wireless Internet access, and private bathrooms.The dormitory is managed by building leaders, floor leaders, and dedicated staff, ensuring proper hygiene and smooth daily operations.",
    image: "/assets/img/china.jpg",
    feeStructure: {
      bachelor: "¥30,000 - ¥30,000",
      masters: "",
      phd: "",
      insurance: "¥800",
      medical: "¥500",
      visa: "¥400",
      accommodation: "¥,4000",
    },
    programs: [
      {
        courseName:
          "Chinese Foundation + Bachelor Computer Science & Technology",
        location: "Beijing, Beijing",
        fee: "Free",
        duration: "4.5 years",
        language: "English",
        intakes: "March 2025",
        applicationDeadline: "20-01-2025",
        image: "/assets/img/logo1.png",
        degreeType: "Undergraduate/Bachelor",
        accommodationFee: "na",
      },
      {
        courseName:
          "Chinese Foundation + Bachelor International Trade & Economics",
        location: "Beijing, Beijing",
        fee: "Free",
        duration: "2 years",
        language: "English",
        intakes: "March 2025",
        applicationDeadline: "20-01-2025",
        image: "/assets/img/logo1.png",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Juris Doctor (JD)",
        location: "Cambridge, Massachusetts, USA",
        image: "/assets/img/logo1.png",
        fee: "$65,000 per year",
        duration: "3 years",
        language: "English",
        intakes: ["Fall"],
        applicationDeadline: "February 15, 2024",
        degreeType: "Undergraduate/Bachelor",
      },
    ],
  },
  {
    id: 2,
    name: "South China University of Technology",
    ranking: 2,
    location: "Guangzhou China",
    about:
      "The South China University of Technology (SCUT) is a leading educational institution in China. It is a public research-intensive university directly governed by the Chinese Ministry of Education. Located in the city of Guangzhou, a thriving metropolis in South China, the university today covers a total area of 391 hectares, consisting of three campuses: the Wushan Campus, the University Town Campus, and the Guangzhou International Campus.The university was formerly known as the South China Institute of Technology, which was first founded in 1952 by merging the engineering schools and departments of several major universities and polytechnic institutes from five provinces, including Guangdong, Guangxi, Hunan, Hubei and Jiangxi. The reorganization, at the time, brought engineering faculties with the strongest academic strengths in the central and southern China together in Guangzhou. The predecessors of this new institute shared long histories of developing modern higher education and scientific research, especially in training students of engineering and technology. The outstanding tradition dates back to the early 20th century, when modern democracy and science were emerging and developing quickly in Guangdong province. In 1960, eight years after the institute's establishment, it was selected by the state as a National Key University. In 1981, it was authorized by the State Council as one of the first institutions in the country to confer doctoral degrees and master degrees. Entering a new stage of history, our faculty will continue to see student cultivation as the ultimate goal in our agenda. SCUT will always hold onto the belief that takes 'the academy as the foundation, talented ones as the strength, open minds as the vitality, and the culture of the university as the energy to thrive and last'. All these efforts are building SCUT as a top-ranking university in the country and a renowned world-class institution.",
    fees: "$52,000 per year",
    image: "/assets/img/southChina.jpg",
    accommodation:
      "South China University of Technology offers a variety of on-campus accommodation options specifically tailored to support the academic and personal needs of international students. The university provides choices between single, double, and quadruple rooms, with pricing based on room type and amenities. The annual costs are: Two-person room: 9,800 CNY per year, Four-person room: 4,300 CNY per year",
    feeStructure: {
      bachelor: "¥26,000 - ¥26,000",
      masters: "",
      phd: "",
      insurance: "¥800",
      medical: "¥400",
      visa: "¥400",
      accommodation: "¥4,300-9,800",
    },
    programs: [
      {
        courseName: "Business Administration (Business Intelligence)",
        location: "Guangdong Province, Guangzhou",
        image: "/assets/img/UniLogo/southChinaLogo.png",
        fee: "¥8,000 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
        accommodationFee: "¥8,000 per year",
      },
      {
        courseName: "Data Science",
        location: "Guangdong Province, Guangzhou",
        image: "/assets/img/UniLogo/southChinaLogo.png",
        fee: "¥8,000 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "International Economics and Trade",
        location: "Guangdong Province, Guangzhou",
        image: "/assets/img/UniLogo/southChinaLogo.png",
        fee: "¥4,300 per year",
        accommodationFee: "¥4,300 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Computer Science and Technology",
        location: "Guangdong Province, Guangzhou",
        image: "/assets/img/UniLogo/southChinaLogo.png",
        fee: "¥0",
        accommodationFee: "¥0",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Artificial Intellignce",
        location: "Guangdong Province, Guangzhou",
        image: "/assets/img/UniLogo/southChinaLogo.png",
        fee: "¥8,000",
        accommodationFee: "¥8,000",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Intelligent Manufacturing Engneering",
        location: "Guangdong Province, Guangzhou",
        image: "/assets/img/UniLogo/southChinaLogo.png",
        fee: "¥8,000",
        accommodationFee: "¥8,000",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Biomedical Engneering",
        location: "Guangdong Province, Guangzhou",
        image: "/assets/img/UniLogo/southChinaLogo.png",
        fee: "¥8,000",
        accommodationFee: "¥8,000",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Robot Engneering",
        location: "Guangdong Province, Guangzhou",
        image: "/assets/img/UniLogo/southChinaLogo.png",
        fee: "¥8,000 per year",
        accommodationFee: "¥8,000 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
    ],
  },
  {
    id: 3,
    name: "Harbin Institute of Technology",
    ranking: 160,
    location: "Shenzhen, Guangdong Province",
    about:
      "Harbin Institute of Technology, Shenzhen (HIT Shenzhen) was founded in 2002, Harbin Institute of Technology Shenzhen address. It is a branch campus of HIT for full-time undergraduate, graduate programs, and part-time programs. HIT Shenzhen has integrated the Shenzhen spirit into the practice of HIT's motto,'Strictest Standard, Greatest Effort'. It remains sensitive to social needs and international academic trends, and pursues high quality in teaching, academic research, administration, and community services. HIT Shenzhen has been committing itself to promoting regional economic development by providing technical and personnel support to industry industries, earning itself a high reputation and full support from the Shenzhen Government and HIT. HIT Shenzhen is always an integral part of the 'Greater HIT Strategy'.Only international students out of China who want to study for a master's or PhD degree can apply for the HIT Independent Recruitment Program. HIT Independent Recruitment Program covers tuition, accommodation, stipends and insurance fees. It is one of the programs of the Chinese Government Scholarship (hereinafter referred to as CSC scholarship) and assigned by the Ministry of Education (hereinafter referred to as MOE) to the university to recruit outstanding international students. Applicants need to submit the application materials according to school requirements. HIT Shenzhen will select the best applicants and recommend them to the China Scholarship Council.",
    fees: "$53,000 per year",
    image: "/assets/img/UniLogo/harbinUni.png",
    programs: [
      {
        courseName: "Bachelor in Computer Science & Technology",
        location: "Guangdong Province, Shenzhen",
        image: "/assets/img/UniLogo/harbin.jpg",
        fee: "$500 per year",
        accommodationFee: "¥500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Communication Engineering",
        location: "Guangdong Province, Shenzhen",
        image: "/assets/img/UniLogo/harbin.jpg",
        fee: "$500 per year",
        accommodationFee: "¥500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Optoelectronic Information Science & Engineering",
        location: "Guangdong Province, Shenzhen",
        image: "/assets/img/UniLogo/harbin.jpg",
        fee: "$500 per year",
        accommodationFee: "¥500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Electronic Packaging Technology",
        location: "Guangdong Province, Shenzhen",
        image: "/assets/img/UniLogo/harbin.jpg",
        fee: "$5,00 per year",
        accommodationFee: "¥500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Urban Planning",
        location: "Guangdong Province, Shenzhen",
        image: "/assets/img/UniLogo/harbin.jpg",
        fee: "$5,00 per year",
        accommodationFee: "¥500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Robotics Engineering",
        location: "Guangdong Province, Shenzhen",
        image: "/assets/img/UniLogo/harbin.jpg",
        fee: "$5,00 per year",
        accommodationFee: "¥500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Mechanical Design Manufacturing & Automation",
        location: "Guangdong Province, Shenzhen",
        image: "/assets/img/UniLogo/harbin.jpg",
        fee: "$5,00 per year",
        accommodationFee: "¥500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Automation",
        location: "Guangdong Province, Shenzhen",
        image: "/assets/img/UniLogo/harbin.jpg",
        fee: "$5,00 per year",
        accommodationFee: "¥500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Electrical Engineering and Automation",
        location: "Guangdong Province, Shenzhen",
        image: "/assets/img/UniLogo/harbin.jpg",
        fee: "$5,00 per year",
        accommodationFee: "¥500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Economics",
        location: "Guangdong Province, Shenzhen",
        image: "/assets/img/UniLogo/harbin.jpg",
        fee: "$5,00 per year",
        accommodationFee: "¥500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Communication Engineering",
        location: "Guangdong Province, Shenzhen",
        image: "/assets/img/UniLogo/harbin.jpg",
        fee: "$5,00 per year",
        accommodationFee: "¥500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "June",
        degreeType: "Undergraduate/Bachelor",
      },
    ],
  },
  {
    id: 4,
    name: "Sichuan Univeristy",
    ranking: 217,
    location: "Chengdu, Sichuan Province",
    about:
      "Sichuan University Scholarship, (SCU) is a prestigious and comprehensive university located in Chengdu, China, directly under the Ministry of Education. It stands out as a top institution under China's Double First-Class Initiative. SCU was formed by merging three prominent universities: Sichuan University, Chengdu University of Science and Technology, and West China University of Medical Sciences, each with a rich history. Sichuan University Admission, SCU offers various programs in disciplines like science, engineering, medicine, economics, and humanities. It has 36 discipline-based colleges and a School of Overseas Education, supporting nearly 66,000 students, including many international students. The university is renowned for its research achievements in fields like engineering, mathematics, clinical medicine, and more, boasting state-level key labs and centers for cutting-edge research. International cooperation is a major focus of SCU. It collaborates with over 268 universities and research institutes worldwide. It has established joint programs and research platforms, such as the SCU-Pittsburgh Institute and the SCU-Hong Kong Polytechnic University Institute for Disaster Management. Sichuan University Scholarship.",
    accommodation:
      "Sichuan University provides dormitories for international students in Wangjiang, Huaxi, and Jiang’an campuses. Due to the limited amount of rooms, students admitted by Sichuan University should apply to on-campus dormitories. Students can also find an apartment outside the campus based on their own needs. ",
    image: "/assets/img/UniLogo/sichuanUni.png",
    feeStructure: {
      bachelor: "¥17,000 - ¥22,000",
      masters: "¥22,000 - ¥39,000",
      phd: "¥26,000 - ¥60,000",
      insurance: "",
      medical: "",
      visa: "",
      accommodation: "",
    },
    programs: [
      {
        courseName: "Bachelor in International Business Management (IBM)",
        location: "Sichuan Province, Chengdu",
        image: "/assets/img/UniLogo/sichuanLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "May",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Bachelor in International Tourism and Hotel Management",
        location: "Sichuan Province, Chengdu",
        image: "/assets/img/UniLogo/sichuanLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "May",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Bachelor in Civil Engineering",
        location: "Sichuan Province, Chengdu",
        image: "/assets/img/UniLogo/sichuanLogo.png",
        fee: "¥5,000",
        accommodationFee: "¥3,000 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "May",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Bachelor in Software Engineering",
        location: "Sichuan Province, Chengdu",
        image: "/assets/img/UniLogo/sichuanLogo.png",
        fee: "¥5,000 per year",
        accommodationFee: "¥3,000 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "May",
        degreeType: "Undergraduate/Bachelor",
      },
    ],
  },
  {
    id: 5,
    name: "Zhejiang University of Technology",
    ranking: 560,
    location: "Hangzhou, Zhejiang, China",
    about:
      "The Zhejiang University of Technology (ZJUT) is a comprehensive key university owned by the Zhejiang Provincial Government, and it was established in the Year 1953. The history of the University can be traced back to 1910, when the Zhejiang Intermediate School of Technology was first founded. The ZJUT is situated in Hangzhou, a picturesque historical and cultural city in China. As a century-old university, ZUT has gone through various historical periods, namely Hangzhou Chemical Engineering School, Zhejiang Secondary Chemical School, Zhejiang Chemical College, and Zhejiang Engineering College. The University now consists of 3 campuses, covering a total area of over 213 hectares, with a floor space of 840,000 square meters. It has 22 colleges and 2 departments, namely the College of Chemical and Material Engineering, College of Mechanical Engineering, College of Civil Engineering and Architecture, College of Information Engineering, College of Computing Science/Software, College of Business and Administration, College of Biological and Environmental Engineering, College of Humanities, College of Art, International College, College of Science, College of Foreign Studies, College of Law, College of Pharmaceutical Science, Zhejiang College, Jianxing College, College of Politics and Public Administration, College of Educational Science and Technology, College of Adult Education, Department of Morality and Politics and Department of Physical Education and Military Training. The present University, as a provincial key comprehensive university, offers not only engineering courses, but also a large range of disciplines like science, liberal arts, law, agriculture, philosophy, economics, pharmaceutical science, management, education, and art. With a national key laboratory and a post-doctoral program, the University is entitled to confer degrees of master's, doctorate, and MBA. In addition, it has been granted the right to recommend outstanding undergraduates as candidates for graduate programs in other universities without entrance examinations and the right to recruit international students as well as students from Hong Kong, Macao, and Taiwan.At present, there are about 30,000 full-time students, including 6,541 postgraduate students and 363 PhD candidates. Besides, there are also around 20,000 part-time students. Currently, more than 800 international students from many countries are studying at ZJUT. The University has a staff of 3,200, amongst whom over 390 are professors, 880 are associate professors, and 790 have PhD degrees. Now ZJUT has one academician of CAE (Chinese Academy of Engineering) and three academicians of CAE and CAS (Chinese Academy of Sciences) whom ZJUT shares with other institutions. The University has around 20 PhD programs, 120 postgraduate programs, and 60 undergraduate programs. The value of its assets totals about RMB 2.69 billion. Its 60,000-square-metre library houses over 5.3 million books (incl. electronic books) and over 17,000 kinds of Chinese and foreign journals.",
    fees: "$53,000 per year",
    accommodation:
      "Single Room: Offers privacy for one student, suitable for those who prefer a quiet space. Double Room: Shared with one other student, providing an opportunity for social interaction at a more affordable cost. Suite-Style Rooms: Some dorms offer suite-style rooms with shared living spaces, bathrooms, and kitchens for small groups of students.",
    image: "/assets/img/UniLogo/zhejianUni.jpg",
    feeStructure: {
      bachelor: "¥16,200 - ¥18,800",
      masters: "¥22,600 - ¥24,000",
      phd: "¥25,000 - ¥27,800",
      insurance: "¥1,000",
      medical: "¥500",
      visa: "¥400",
      accommodation: "¥3,500 - ¥5,300",
    },
    programs: [
      {
        courseName: "International Economics and Trade",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/zhejianLogo.png",
        fee: "¥4,500 per year",
        accommodationFee: "¥4,500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "July",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Civil Engineering",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/zhejianLogo.png",
        fee: "¥4,500 per year",
        accommodationFee: "¥4,500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "July",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Computer Science and Technology",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/zhejianLogo.png",
        fee: "¥4,500 per year",
        accommodationFee: "¥4,500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "July",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Software Engineering",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/zhejianLogo.png",
        fee: "¥4,500 per year",
        accommodationFee: "¥4,500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "July",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Mechanical Engineering",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/zhejianLogo.png",
        fee: "¥4,500 per year",
        accommodationFee: "¥4,500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "July",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Chemical Engineering and Technology",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/zhejianLogo.png",
        fee: "¥4,500 per year",
        accommodationFee: "¥4,500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "July",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Undergraduate Preparatory Program",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/zhejianLogo.png",
        fee: "¥11,800 per year",
        accommodationFee: "¥2,400 per year",
        duration: "0.4 years",
        language: "English",
        intakes: "March",
        applicationDeadline: "Jan",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Finance",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/zhejianLogo.png",
        fee: "¥4,500 per year",
        accommodationFee: "¥4,500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "July",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Electrical Engineering and Automation",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/zhejianLogo.png",
        fee: "¥4,500 per year",
        accommodationFee: "¥4,500 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "July",
        degreeType: "Undergraduate/Bachelor",
      },
    ],
  },
  {
    id: 6,
    name: "Wuhan Institute of Technology",
    ranking: "901 - 1000",
    location: "Wuhan, Hubei, China",
    about:
      "Wuhan Institute of Technology (WIT), established in 1972 as Hubei Petrochemical Institute, initially focused on chemical engineering under provincial administration. The Wuhan Institute of Chemical Technology (WICT) was renamed in 1980 and was then managed by the Ministry of Chemical Industry. In 1998, WICT transitioned to a joint central-provincial administration, focusing more on provincial needs. By 2006, it was renamed Wuhan Institute of Technology (WIT) as it expanded to a multidisciplinary institution. The same year, WIT received an 'A' grade in the Ministry of Education's national evaluation, solidifying its reputation for academic excellence. WIT offers a range of programs for undergraduates, postgraduates, and junior college students across various disciplines. With over 18,000 full-time students from 30 provinces, WIT provides engineering, science, management, economics, arts, and law degrees, with a notable emphasis on engineering and management. The institution includes 14 schools, one department, and a research institute, offering 48 specialties. WIT’s programs emphasize high-quality education, with several nationally and provincially recognized disciplines. The university employs 1,793 staff members, including 1,115 teachers and researchers. Among its faculty, 46.5% hold senior professional titles, with 17.3% holding doctoral degrees, reflecting WIT's focus on academic quality and research. WIT has developed initiatives like the 'WIT Scholar Project,' which attracts top international professors and fosters a diverse academic environment. Research at WIT is substantial, with 2,200 projects completed recently, including 59 national-level and 426 provincial-level projects. WIT’s awards include a national second prize in scientific progress and a second prize in technical invention. These projects, along with substantial research funding, rank WIT among the leading institutions in Hubei Province. Wuhan Institute of Technology stands as a leader in higher education, offering diverse programs, fostering research excellence, and emphasizing moral development. Its academic rigor, coupled with strong industry and international ties, prepares students for meaningful careers. WIT’s commitment to quality education, research, and community service makes it a cornerstone of higher learning in Hubei Province and a respected institution nationwide.",
    fees: "$53,000 per year",
    accommodation:
      "2-Bed Room: Shared with one other student, offering a more private living arrangement. 4-Bed Room: Shared with three other students, providing a more communal and cost-effective option. Basic Room Amenities: Each room typically includes beds, desks, chairs, wardrobes, and access to high-speed internet (Wi-Fi or LAN). Air Conditioning and Heating: Available to ensure comfort in all seasons. Shared Bathroom: Rooms often include a shared bathroom or access to communal bathrooms within the dormitory.",
    image: "/assets/img/UniLogo/wuhanUni.png",
    feeStructure: {
      bachelor: "¥6,000 - ¥12,000",
      masters: "¥10,000 - ¥20,000",
      phd: "",
      insurance: "¥800",
      medical: "¥340",
      visa: "¥500",
      accommodation: "¥1,000 - ¥2,000",
    },
    programs: [
      {
        courseName: "Pharmaceutical Engineering",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/wuhanLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "March",
        applicationDeadline: "December",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Mining Engineering",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/wuhanLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "March",
        applicationDeadline: "December",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Computer Science and Engineering",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/wuhanLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "March",
        applicationDeadline: "December",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Civil Engineering",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/wuhanLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "March",
        applicationDeadline: "December",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Internation Economics and Trade",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/wuhanLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "March",
        applicationDeadline: "December",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Mechanical Engineering",
        location: "Zhejiang Province, Hangzhou",
        image: "/assets/img/UniLogo/wuhanLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "March",
        applicationDeadline: "December",
        degreeType: "Undergraduate/Bachelor",
      },
    ],
  },

  {
    id: 7,
    name: "Tongji University",
    ranking: "NA",
    location: "Shanghai, China",
    about:
      "Tongji University Scholarship, located in Shanghai , is a national key university directly under the Ministry of Education of the People's Republic of China and a centrally administered university.It is a Double First-Class A-level university, a 985 Project , and a 211 Project university. The school has been selected for the Everest Project , the 101 Project , the Strong Foundation Project, the Elite Talent Project, the 2011 Project, the 111 Project , the Excellent Engineer Education and Training Program , the Excellent Legal Talent Education and Training Program , the Excellent Doctor Education and Training Program , the National Undergraduate Innovation Experimental Program , the National High-level University Construction Government-sponsored Graduate Program , the Chinese Government Scholarship Receiving University for International Students , the National Undergraduate Innovation and Entrepreneurship Training Program , the National Demonstration Base for the Training of Innovative Talents , the New Engineering Research and Practice Project , the National Demonstration University for Deepening Innovation and Entrepreneurship Education Reform , the first batch of independent degree authorization review units , the United Nations Environment Programme Global Environment and Sustainable Development University Cooperation Alliance Chair Unit, the 21st Century Academic Alliance , the International Design and Art Schools Alliance , the International Railway Union , the China-Russia Engineering University Alliance , the China-Europe Engineering Education Platform , the Excellent University Alliance , the Pacific Rim University Association , and the International Green Campus Alliance. Tongji University Scholarship, The university was originally founded by Erich Paulun in Shanghai in 1907 as the German Medical School . In 1908, it was renamed Tongji German Medical School . In 1912, it was combined with Tongji German Engineering School to become Tongji Medical and Engineering School . In 1923, it was officially named Tongji University. In 1927, it became National Tongji University , one of China's first seven national universities.",
    fees: "$53,000 per year",
    accommodation:
      "Students can book nearby hotels around Tongji University. Due to the limited availability, early booking is recommended.",
    image: "/assets/img/UniLogo/tongjiUni.png",
    feeStructure: {
      bachelor: "",
      masters: "",
      phd: "",
      insurance: "",
      medical: "",
      visa: "",
      accommodation: "",
    },
    programs: [],
  },
  {
    id: 8,
    name: "Shanghai Jiao Tong University",
    ranking: "45",
    location: "Shanghai, China",
    about:
      "Shanghai Jiao Tong University (SJTU) is a world-renowned higher education institution and one of the top universities in China Shanghai Jiao Tong University Scholarship for International students. It has established itself as a comprehensive, research-oriented, and internationalized university and ranks 45th worldwide (QS 2025). SJTU has 34 schools/departments, 12 affiliated hospitals, 13 affiliated research institutes, 23 directly affiliated units and 5 directly affiliated enterprises, with 18,004 full-time undergraduates, 28,439 full-time master's degree candidates, and 1,858 overseas students. SJTU faculty includes 3,887 full-time teachers, 30 members of the Chinese Academy of Sciences, and 27 members of the Chinese Academy of Engineering. As a comprehensive university, SJTU offers 75 undergraduate programs covering 9 major disciplines: economics, law, literature, science, engineering, agriculture, medicine, management, and arts. Shanghai Jiao Tong University Scholarship 2025.",
    accommodation:
      "Shanghai Jiaotong University dormitories are well-equipped to ensure a comfortable and convenient living environment for students. Each room comes fully furnished with essential items such as beds, desks, chairs, and storage spaces, allowing students to feel at home from the moment they arrive. The dormitories also offer high-speed Wi-Fi access, ensuring that students can stay connected for both academic and personal communication needs. To maintain comfort during warmer months, all rooms are equipped with air conditioning units. In addition to private living spaces, the dormitories feature a range of shared amenities. Common areas are available in each dormitory block, providing spaces for students to relax and socialize. Laundry rooms with washing machines are also accessible for student use, and some dormitories include shared kitchenettes where students can prepare their own meals. Security and management are prioritized within the dormitory facilities. With 24/7 security personnel and CCTV monitoring, students can feel safe and well-protected. The dormitories are strategically located within close proximity to academic buildings, libraries, dining halls, and recreational facilities, ensuring that students can conveniently access all necessary campus services. Overall, these facilities contribute to a well-rounded living experience that supports both the academic success and personal development of students at Shanghai Jiaotong University.",
    image: "/assets/img/UniLogo/shanghaiUni.png",
    feeStructure: {
      bachelor: "¥24,800-¥80,000",
      masters: "¥28,900-¥45,500",
      phd: "¥35,000-¥45,000",
      insurance: "¥800",
      medical: "¥400",
      visa: "¥600",
      accommodation: "¥4,800 - ¥5,400",
    },
    programs: [
      {
        courseName: "Computer Science and Technology",
        location: "Shanghai, Shanghai",
        image: "/assets/img/UniLogo/shanghaiLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English, Chinese",
        intakes: "September",
        applicationDeadline: "October",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Electrical and Computer Engineering",
        location: "Shanghai, Shanghai",
        image: "/assets/img/UniLogo/shanghaiLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "November",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Mechanical Engineering",
        location: "Shanghai, Shanghai",
        image: "/assets/img/UniLogo/shanghaiLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "March",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Material Science and Engineering",
        location: "Shanghai, Shanghai",
        image: "/assets/img/UniLogo/shanghaiLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "March",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Information Engineering",
        location: "Shanghai, Shanghai",
        image: "/assets/img/UniLogo/shanghaiLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "March",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Automation",
        location: "Shanghai, Shanghai",
        image: "/assets/img/UniLogo/shanghaiLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "March",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Naval Architecture and Ocean Engineering",
        location: "Shanghai, Shanghai",
        image: "/assets/img/UniLogo/shanghaiLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "March",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Power and Energy Engineering",
        location: "Shanghai, Shanghai",
        image: "/assets/img/UniLogo/shanghaiLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "March",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Civil Engineering",
        location: "Shanghai, Shanghai",
        image: "/assets/img/UniLogo/shanghaiLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "2 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "March",
        degreeType: "Masters",
      },
      {
        courseName: "Transportation Engineering",
        location: "Shanghai, Shanghai",
        image: "/assets/img/UniLogo/shanghaiLogo.png",
        fee: "Free",
        accommodationFee: "¥0 per year",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "March",
        degreeType: "Masters",
      },
    ],
  },
  {
    id: 9,
    name: "Chongqing Medical University",
    ranking: "NA",
    location: "Chongqing, China",
    about:
      "Shanghai Jiao Tong University (SJTU) is a world-renowned higher education institution and one of the top universities in China Shanghai Jiao Tong University Scholarship for International students. It has established itself as a comprehensive, research-oriented, and internationalized university and ranks 45th worldwide (QS 2025). SJTU has 34 schools/departments, 12 affiliated hospitals, 13 affiliated research institutes, 23 directly affiliated units and 5 directly affiliated enterprises, with 18,004 full-time undergraduates, 28,439 full-time master's degree candidates, and 1,858 overseas students. SJTU faculty includes 3,887 full-time teachers, 30 members of the Chinese Academy of Sciences, and 27 members of the Chinese Academy of Engineering. As a comprehensive university, SJTU offers 75 undergraduate programs covering 9 major disciplines: economics, law, literature, science, engineering, agriculture, medicine, management, and arts. Shanghai Jiao Tong University Scholarship 2025.",
    accommodation:
      "Shanghai Jiaotong University dormitories are well-equipped to ensure a comfortable and convenient living environment for students. Each room comes fully furnished with essential items such as beds, desks, chairs, and storage spaces, allowing students to feel at home from the moment they arrive. The dormitories also offer high-speed Wi-Fi access, ensuring that students can stay connected for both academic and personal communication needs. To maintain comfort during warmer months, all rooms are equipped with air conditioning units. In addition to private living spaces, the dormitories feature a range of shared amenities. Common areas are available in each dormitory block, providing spaces for students to relax and socialize. Laundry rooms with washing machines are also accessible for student use, and some dormitories include shared kitchenettes where students can prepare their own meals. Security and management are prioritized within the dormitory facilities. With 24/7 security personnel and CCTV monitoring, students can feel safe and well-protected. The dormitories are strategically located within close proximity to academic buildings, libraries, dining halls, and recreational facilities, ensuring that students can conveniently access all necessary campus services. Overall, these facilities contribute to a well-rounded living experience that supports both the academic success and personal development of students at Shanghai Jiaotong University.",
    image: "/assets/img/UniLogo/chongqingUni.jpg",
    feeStructure: {
      bachelor: "",
      masters: "",
      phd: "",
      insurance: "",
      medical: "",
      visa: "",
      accommodation: "",
    },
    programs: [
      {
        courseName: "Bachelor of Medicine & Bachelor of Surgery",
        location: "Shanghai, Shanghai",
        image: "/assets/img/UniLogo/chongqingLogo.png",
        fee: "¥34,800",
        accommodationFee: "¥4,800 per year",
        duration: "6 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "-",
        degreeType: "Bachelor",
      },
    ],
  },
  {
    id: 10,
    name: "Tianjin University",
    ranking: "281",
    location: "Tianjin, China",
    about:
      "Tianjin University is a National Key University directly under the administration of the Ministry of the Education, and its history can be traced back to Peiyang University, the first modern university in China, which was founded on October 2, 1895. It was renamed Tianjin University after the nationwide restructuring of colleges and departments in 1951. In 1959, Tianjin University was identified as one of the first batch of the 16 National Key Universities designated by the government, and it is also among the first group of institutions of higher learning to be included in the '211' and '985' Projects of national investment for developing world class universities. During the past years, Tianjin University has made significant contributions to economic and social development, which must be due to its cultivation of a large number of high-level talents, and its outstanding achievements. To build a strong nation, the education system must be set up and developed for the preservation of talent. The establishment and operation of the University aim to promote education for the ultimate improvement of national strength and prosperity, in accord with the University's motto of 'Seeking Truth from Facts'. The University exalts preserving its own traditions, in which the spirit of 'precision in learning and strictness in teaching' is encouraged. Patriotism and devotion to the country are also considered worthy goals to hold onto, tied in with multiple avenues to encourage undaunted inquiry into academic truth, to foster competent talent, to pass on the cultural heritages, to buttress the progress of our nation, and to create a promising future. Tianjin University will uphold its people-oriented vision, promote comprehensive reform in an all-round way, constantly improve the systems of a modern university, and strive vigorously toward the goal of becoming a world-class university with Chinese characteristics and TJU traits.",
    accommodation:
      "The Institute of International Education at Tianjin University offers a variety of dormitory options across its Weijin Road and Peiyang Garden campuses, with a total of seven apartment buildings designated for overseas students. At the Weijin Road Campus, the Youyuan Building has six floors consisting entirely of single rooms. It features a service desk in the hall and includes 12 classrooms. The first floor provides public toilets and a self-service laundry room for student convenience. Liuyuan Building is divided into four districts: A, B, C, and D. Liuyuan A consists of five floors of double rooms, with a service desk in the hall and four classrooms. Bathrooms and shower rooms on the first and second floors are for girls, while the upper three floors are designated for boys. The building also includes a self-service laundry room on the second floor and public kitchens from the second to fifth floors. Liuyuan B also has five floors of double rooms, with a public toilet on the first floor. Bathroom and shower facilities on the third floor are for girls, and those on the fourth floor are for boys. Liuyuan C is primarily a special classroom area with multi-functional conference rooms and classrooms on the second floor, and an additional 11 classrooms on the third floor. Liuyuan D offers five floors of double rooms with a service desk in the hall. It includes a total of eight classrooms distributed across three floors, a conference room on the second floor, and a self-service laundry room on the third floor. The Expert Building, also located on the Weijin Road Campus, has four floors of double rooms. It includes a service desk, a public toilet on the first floor, and a self-service laundry room on the second floor. 50 Zhai is another six-story dormitory building featuring only double rooms. It offers a service desk, public kitchens on each floor, and a self-service laundry room on the first floor. Similarly, 51 Zhai has six floors; the first floor contains three- and four-bedroom units, while the second through sixth floors consist of double rooms. Each floor is equipped with a public kitchen, and a self-service laundry room is available on the first floor. Additionally, Liuyuan A at the Peiyang Garden Campus comprises six floors of single rooms. This building includes a service desk, public kitchens on each floor, and a self-service laundry room on the first floor. Clara Hotel, a six-story building with all double rooms, also serves as student accommodation and includes a service desk in the hall. These dormitory facilities are designed to cater to the diverse needs of international students, offering a range of room types, essential amenities, and support services to ensure a comfortable and convenient stay.",
    image: "/assets/img/UniLogo/tianjinUni.jpg",
    feeStructure: {
      bachelor: "¥16,600 - ¥26,000",
      masters: "¥24,900 - ¥39,000",
      phd: "¥33,200 - ¥39,000",
      insurance: "¥800",
      medical: "¥500",
      visa: "¥400",
      accommodation: "¥9,000 - ¥21,600",
    },
    programs: [
      {
        courseName: "Urban Planning",
        location: "Tianjin, Tianjin",
        image: "/assets/img/UniLogo/tianjinLogo.jpg",
        fee: "Free",
        accommodationFee: "¥0",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "March",
        degreeType: "PhD",
      },
      {
        courseName: "Chemical Engineering and Technology",
        location: "Tianjin, Tianjin",
        image: "/assets/img/UniLogo/tianjinLogo.jpg",
        fee: "Free",
        accommodationFee: "¥0",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "April",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Environmental Engineering",
        location: "Tianjin, Tianjin",
        image: "/assets/img/UniLogo/tianjinLogo.jpg",
        fee: "Free",
        accommodationFee: "¥0",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "April",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Pharmaceutical Science",
        location: "Tianjin, Tianjin",
        image: "/assets/img/UniLogo/tianjinLogo.jpg",
        fee: "Free",
        accommodationFee: "¥0",
        duration: "4 years",
        language: "English",
        intakes: "September",
        applicationDeadline: "April",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Material Science and Engineering",
        location: "Tianjin, Tianjin",
        image: "/assets/img/UniLogo/tianjinLogo.jpg",
        fee: "Free",
        accommodationFee: "¥0",
        duration: "4 years",
        language: "Chinese",
        intakes: "September",
        applicationDeadline: "April",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Materials Forming and Control Engineering",
        location: "Tianjin, Tianjin",
        image: "/assets/img/UniLogo/tianjinLogo.jpg",
        fee: "Free",
        accommodationFee: "¥0",
        duration: "4 years",
        language: "Chinese",
        intakes: "September",
        applicationDeadline: "April",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Geographical Science",
        location: "Tianjin, Tianjin",
        image: "/assets/img/UniLogo/tianjinLogo.jpg",
        fee: "Free",
        accommodationFee: "¥0",
        duration: "4 years",
        language: "Chinese",
        intakes: "September",
        applicationDeadline: "April",
        degreeType: "Undergraduate/Bachelor",
      },
      {
        courseName: "Electrical Engineering an Automation",
        location: "Tianjin, Tianjin",
        image: "/assets/img/UniLogo/tianjinLogo.jpg",
        fee: "Free",
        accommodationFee: "¥0",
        duration: "4 years",
        language: "Chinese",
        intakes: "September",
        applicationDeadline: "April",
        degreeType: "Undergraduate/Bachelor",
      },
    ],
  },
];
